# Generated by Django 4.2.11 on 2025-04-03 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View_Assistenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Nº')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('image', models.CharField(max_length=4, verbose_name='Icone')),
                ('ult_entrega', models.DateField(verbose_name='Entrega')),
                ('prox_entrega', models.DateField(verbose_name='Próx. Entrega')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
                ('criado', models.DateField(verbose_name='Cadastro')),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
            ],
            options={
                'verbose_name': '13-Listagem de Assistenciado',
                'verbose_name_plural': '13-Listagem de Assistenciados',
                'db_table': 'view_assistenciado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assistenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(default='-', max_length=100, verbose_name='Telefone')),
                ('nascimento', models.DateField(null=True, verbose_name='Data Nasc.')),
                ('numero', models.IntegerField(verbose_name='Nº')),
                ('observacao', models.TextField(default='-', verbose_name='Informações adicionais')),
            ],
            options={
                'verbose_name': '08-Assistenciado',
                'verbose_name_plural': '08-Assistenciados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': '05-Bairro',
                'verbose_name_plural': '05-Bairros',
                'ordering': ['bairro'],
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Entregador')),
            ],
            options={
                'verbose_name': '09-Entregador',
                'verbose_name_plural': '09-Entregadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': '10-Fornecedor',
                'verbose_name_plural': '10-Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('local', models.CharField(max_length=100, verbose_name='Localização')),
            ],
            options={
                'verbose_name': '01-Local do Estoque',
                'verbose_name_plural': '01-Locais do Estoque',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': '07-Ocupação',
                'verbose_name_plural': '07-Ocupações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('prazo', models.IntegerField(verbose_name='Prazo para Entrega')),
                ('image', models.CharField(max_length=5, verbose_name='Icone')),
            ],
            options={
                'verbose_name': '04-Período de Entrega',
                'verbose_name_plural': '04-Períodos de Entrega',
                'ordering': ['prazo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estoqueinicial', models.IntegerField(default=0, verbose_name='Estoque Inicial')),
                ('localestoque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.localestoque', verbose_name='Local')),
            ],
            options={
                'verbose_name': '03-Produto',
                'verbose_name_plural': '03-Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=10, verbose_name='Unidade')),
            ],
            options={
                'verbose_name': '02-Unidade de Medida ',
                'verbose_name_plural': '02-Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cor_id', models.IntegerField()),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('recebeu', models.CharField(max_length=50, verbose_name='Quem Recebeu?')),
                ('dataentrega', models.DateField(default=datetime.datetime(2025, 4, 3, 22, 23, 50, 28316, tzinfo=datetime.timezone.utc), verbose_name='Data da Entrega')),
                ('assistenciado', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saida_assistenciado', to='core.assistenciado', verbose_name='Recebedor')),
                ('entregador', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='core.entregador', verbose_name='Entregador')),
                ('produto', models.ForeignKey(default=1, limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': '11-Entrega',
                'verbose_name_plural': '11-Entregas',
                'ordering': ['-dataentrega', 'assistenciado'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.unidade', verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade', models.IntegerField()),
                ('dataentrega', models.DateField(default=datetime.datetime(2025, 4, 3, 22, 23, 50, 27316, tzinfo=datetime.timezone.utc), verbose_name='Data Recebimento')),
                ('notafiscal', models.IntegerField(default=0, verbose_name='Nº Nota Fiscal')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': '12-Recebimento',
                'verbose_name_plural': '12-Recebimentos',
                'ordering': ['-dataentrega'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.bairro', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': '06-Endereço',
                'verbose_name_plural': '06-Endereços',
                'ordering': ['endereco'],
            },
        ),
        migrations.AddField(
            model_name='assistenciado',
            name='endereco',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enderecos', to='core.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='assistenciado',
            name='ocupacao',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.AddField(
            model_name='assistenciado',
            name='periodo',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assistenciados', to='core.periodo', verbose_name='Cor'),
        ),
    ]
