# Generated by Django 4.2.11 on 2025-04-03 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='dataentrega',
            field=models.DateField(default=datetime.datetime(2025, 4, 3, 22, 28, 35, 825945, tzinfo=datetime.timezone.utc), verbose_name='Data Recebimento'),
        ),
        migrations.AlterField(
            model_name='saidaproduto',
            name='dataentrega',
            field=models.DateField(default=datetime.datetime(2025, 4, 3, 22, 28, 35, 825945, tzinfo=datetime.timezone.utc), verbose_name='Data da Entrega'),
        ),
    ]
