# Generated by Django 4.2.11 on 2025-04-03 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entradaproduto_dataentrega_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': '10-Fornecedor/Doador', 'verbose_name_plural': '10-Fornecedores/Doadores'},
        ),
        migrations.AddField(
            model_name='entradaproduto',
            name='observacao',
            field=models.TextField(default=0, verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='dataentrega',
            field=models.DateField(default=datetime.datetime(2025, 4, 3, 22, 36, 25, 505044, tzinfo=datetime.timezone.utc), verbose_name='Data Recebimento'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='fornecedor',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fornecedor', verbose_name='Fornecedor/Doador'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='notafiscal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='saidaproduto',
            name='dataentrega',
            field=models.DateField(default=datetime.datetime(2025, 4, 3, 22, 36, 25, 505044, tzinfo=datetime.timezone.utc), verbose_name='Data da Entrega'),
        ),
    ]
